# Generated by Django 3.2.10 on 2021-12-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityTags',
            new_name='ActivityTag',
        ),
    ]
