# Generated by Django 3.2.10 on 2022-01-19 12:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211223_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawUsageAllFieldsAllTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('usage_time', models.TimeField()),
                ('data_consumer_pk', models.IntegerField()),
                ('data_consumer_email', models.CharField(max_length=400)),
                ('data_consumer_job_title_pk', models.IntegerField()),
                ('data_consumer_job_title', models.CharField(max_length=400)),
                ('activity_tag_pks', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True), size=None)),
                ('activity_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=400), size=None)),
                ('entity_pk', models.IntegerField()),
                ('entity_name', models.CharField(max_length=400)),
                ('location_pk', models.IntegerField()),
                ('location_country', models.CharField(max_length=400)),
                ('location_city', models.CharField(max_length=400)),
                ('location_state', models.CharField(max_length=400)),
                ('bbg_uuid_pk', models.IntegerField()),
                ('bbg_uuid', models.CharField(max_length=400)),
                ('bbg_subscription_pk', models.IntegerField()),
                ('bbg_subscription', models.CharField(max_length=400)),
                ('bbg_account_pk', models.IntegerField()),
                ('bbg_account_number', models.CharField(max_length=400)),
                ('bbg_firm_pk', models.IntegerField()),
                ('bbg_firm_number', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'raw_usage_all_fields_all_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DefaultAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
