# Generated by Django 3.2.10 on 2022-01-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_defaultavatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloomberguuid',
            name='data_consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_consumers', to='api.dataconsumer'),
        ),
        migrations.CreateModel(
            name='InstalledTrackers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bloomberg Anywhere Tracker', max_length=400)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.bloomberguuid')),
            ],
        ),
    ]
