# Generated by Django 3.2.10 on 2021-12-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_activitytags_activitytag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconsumer',
            name='internal_id',
            field=models.CharField(blank=True, help_text='ID from your organizations ERP/HR system', max_length=200, null=True),
        ),
    ]
