# Generated by Django 3.2.10 on 2021-12-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dataconsumer_internal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalentity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationalentity',
            name='location',
            field=models.ManyToManyField(blank=True, help_text='It is preferred to only use this field, when the entity is best described by only one location', null=True, to='api.BusinessLocation'),
        ),
    ]
