# Generated by Django 3.2.10 on 2021-12-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211213_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloomberguuid',
            old_name='bbg_uuid',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='bloombergserialnumber',
            name='serial_numner',
            field=models.CharField(default='', help_text='Each instance of software has its own serial number that is unique to that installation. This can be found by hitting the cancel key and the S/N is located at the bottom left corner. All serial number would be associated with an SID number.', max_length=200),
            preserve_default=False,
        ),
    ]
