# Generated by Django 3.2.10 on 2021-12-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationalentity',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
