# Generated by Django 3.2.10 on 2021-12-14 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_parent_id_organizationalentity_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalentity',
            name='location',
        ),
        migrations.AddField(
            model_name='organizationalentity',
            name='location',
            field=models.ForeignKey(blank=True, help_text='It is mandatory to only use this field, when the entity is best described by only one location', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.businesslocation'),
        ),
        migrations.AlterField(
            model_name='organizationalentity',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Choose a parent entity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.organizationalentity'),
        ),
    ]
