# Generated by Django 3.2.10 on 2021-12-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211222_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVendorDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('custom_fields', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomVendorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customvendordefinition')),
            ],
        ),
    ]
