# Generated by Django 3.2.10 on 2021-12-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_customvendordefinition_customvendorvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloombergaccount',
            name='firm_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.bloombergfirm'),
        ),
        migrations.AlterField(
            model_name='bloombergsubscription',
            name='bloomberg_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.bloombergaccount'),
        ),
        migrations.AlterField(
            model_name='bloomberguuid',
            name='bloomberg_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.bloombergsubscription'),
        ),
        migrations.AlterField(
            model_name='bloomberguuid',
            name='data_consumer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_consumers', to='api.dataconsumer'),
        ),
    ]
