# Generated by Django 3.2.10 on 2021-12-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211223_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloomberguuid',
            name='data_consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_consumers', to='api.dataconsumer'),
        ),
    ]
