# Generated by Django 3.2.10 on 2021-12-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_bloomberguuid_data_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloombergaccount',
            name='description',
            field=models.TextField(default='An account number, or a customer number, is created for every location where billable SIDs (licenses), circuits or services are installed. Multiple account numbers can be created in one location if required for billing / administrative purposes.', max_length=4000),
        ),
        migrations.AddField(
            model_name='bloombergaccount',
            name='name',
            field=models.CharField(default='Bloomberg Account Number', max_length=400),
        ),
        migrations.AddField(
            model_name='bloombergfirm',
            name='description',
            field=models.TextField(default="An account must be under a firm number. Firm number can be regarded as the 'umbrella' number under which all related accounts are grouped. These accounts/entities under the same umbrella have to be in a control relationship with one another or under a common control.", max_length=4000),
        ),
        migrations.AddField(
            model_name='bloombergfirm',
            name='name',
            field=models.CharField(default='Bloomberg Firm Number', max_length=400),
        ),
        migrations.AddField(
            model_name='bloombergsubscription',
            name='description',
            field=models.TextField(default='An SID is a unique number which Bloomberg uses to track the progression of a license. SIDs are also linked to any entitlements or exchanges, allowing them to be carried across various actions. SID attached to a service are considered billable and represent one paid license.', max_length=4000),
        ),
        migrations.AddField(
            model_name='bloombergsubscription',
            name='name',
            field=models.CharField(default='Bloomberg Subscription Identifier (SID)', max_length=400),
        ),
        migrations.AddField(
            model_name='bloomberguuid',
            name='description',
            field=models.TextField(default='A UUID is a unique number assigned to every Bloomberg login (username).', max_length=4000),
        ),
        migrations.AddField(
            model_name='bloomberguuid',
            name='name',
            field=models.CharField(default='Unique User Identifier (UUID)', max_length=400),
        ),
        migrations.AlterField(
            model_name='activitytag',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='bloombergaccount',
            name='account_number',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='bloombergfirm',
            name='firm_number',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='bloombergserialnumber',
            name='serial_numner',
            field=models.CharField(help_text='Each instance of software has its own serial number that is unique to that installation. This can be found by hitting the cancel key and the S/N is located at the bottom left corner. All serial number would be associated with an SID number.', max_length=400),
        ),
        migrations.AlterField(
            model_name='bloombergsubscription',
            name='subscription_id',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='bloomberguuid',
            name='uuid',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='city',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='country',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='state',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='street',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='street_nr',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='businesslocation',
            name='zip_code',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='customvendordefinition',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='dataconsumer',
            name='first_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='dataconsumer',
            name='floor',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='dataconsumer',
            name='internal_id',
            field=models.CharField(blank=True, help_text='ID from your organizations ERP/HR system', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='dataconsumer',
            name='last_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='dataconsumer',
            name='seat',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='organizationalentity',
            name='bbg_lei_code',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='app_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
