# Generated by Django 3.2.10 on 2022-01-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_license_installedtrackers_license_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedtrackers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
