# Generated by Django 3.2.10 on 2022-02-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_installedtrackers_created_at'),
    ]

    operations = [
      migrations.RunSQL("""
                        CREATE OR REPLACE VIEW raw_usage_all_fields_all_time AS
                        SELECT api_usage.id,
                          api_usage.start_time,
                          api_usage.end_time,
                          sum(api_usage.end_time - api_usage.start_time)::time without time zone AS usage_time,
                          api_usage.data_consumer_id AS data_consumer_pk,
                          api_dataconsumer.email AS data_consumer_email,
                          api_dataconsumer.job_title_id AS data_consumer_job_title_pk,
                          api_job.title AS data_consumer_job_title,
                          activitytag_pks.activity_tag_pks,
                          activitytags.activity_tags,
                          api_dataconsumer.organizational_entity_id AS entity_pk,
                          api_organizationalentity.name AS entity_name,
                          api_dataconsumer.location_id AS location_pk,
                          api_businesslocation.country AS location_country,
                          api_businesslocation.city AS location_city,
                          api_businesslocation.state AS location_state,
                          api_bloomberguuid.id AS bbg_uuid_pk,
                          api_bloomberguuid.uuid AS bbg_uuid,
                          api_bloombergsubscription.id AS bbg_subscription_pk,
                          api_bloombergsubscription.subscription_id AS bbg_subscription,
                          api_bloombergaccount.id AS bbg_account_pk,
                          api_bloombergaccount.account_number AS bbg_account_number,
                          api_bloombergfirm.id AS bbg_firm_pk,
                          api_bloombergfirm.firm_number AS bbg_firm_number
                        FROM api_usage
                          JOIN api_dataconsumer ON api_usage.data_consumer_id = api_dataconsumer.id
                          JOIN api_organizationalentity ON api_dataconsumer.organizational_entity_id = api_organizationalentity.id
                          JOIN api_businesslocation ON api_dataconsumer.location_id = api_businesslocation.id
                          JOIN api_job ON api_dataconsumer.job_title_id = api_job.id
                          JOIN ( SELECT array_agg(api_activitytag.id) AS activity_tag_pks,
                                  api_dataconsumer_activity.dataconsumer_id AS dataconsumer_pk
                                FROM api_activitytag
                                  JOIN api_dataconsumer_activity ON api_activitytag.id = api_dataconsumer_activity.activitytag_id
                                GROUP BY api_dataconsumer_activity.dataconsumer_id) activitytag_pks ON api_dataconsumer.id = activitytag_pks.dataconsumer_pk
                          JOIN ( SELECT array_agg(api_activitytag.name) AS activity_tags,
                                  api_dataconsumer_activity.dataconsumer_id AS dataconsumer_pk
                                FROM api_activitytag
                                  JOIN api_dataconsumer_activity ON api_activitytag.id = api_dataconsumer_activity.activitytag_id
                                GROUP BY api_dataconsumer_activity.dataconsumer_id) activitytags ON api_dataconsumer.id = activitytags.dataconsumer_pk
                          JOIN api_bloomberguuid ON api_dataconsumer.id = api_bloomberguuid.data_consumer_id
                          JOIN api_bloombergsubscription ON api_bloomberguuid.bloomberg_subscription_id = api_bloombergsubscription.id
                          JOIN api_bloombergaccount ON api_bloombergsubscription.bloomberg_account_id = api_bloombergaccount.id
                          JOIN api_bloombergfirm ON api_bloombergaccount.firm_number_id = api_bloombergfirm.id
                        GROUP BY api_usage.id, api_dataconsumer.email, api_dataconsumer.job_title_id, api_job.title, activitytag_pks.activity_tag_pks, activitytags.activity_tags, api_dataconsumer.organizational_entity_id, api_organizationalentity.name, api_dataconsumer.location_id, api_businesslocation.country, api_businesslocation.city, api_businesslocation.state, api_bloomberguuid.id, api_bloombergsubscription.id, api_bloombergaccount.id, api_bloombergfirm.id
                        ORDER BY api_usage.start_time DESC;
                        """)
    ]
